name: ➕ 新增开源项目
description: 提交一个新的优秀开源项目到收录录
title: "[Add]: 自动解析新项目"
labels: ["auto-add"]
body:
  - type: input
    id: repo_url
    attributes:
      label: GitHub 仓库地址
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: 归属分类 (选择已有)
      options:
        - "☕ Java 生态"
        - "☕ Java 生态 / 开发框架(Spring)"
        - "☕ Java 生态 / ORM 框架"
        - "☕ Java 生态 / idea 插件"
        - "AI"
        - "AI / Skills"
        - "AI / 学习资料"
        - "AI / AI 编程助手 & 桌面客户端"
        - "🗄️ 数据库"
        - "🗄️ 数据库 / 客户端管理工具"
        - "🗄️ 数据库 / 关系型数据库"
        - "🗄️ 数据库 / 向量数据库"
        - "文档工具"
        - "文档工具 / 知识库&个人笔记"
        - "🌐 分布式"
        - "🌐 分布式 / RPC 框架"
        - "🛠️ 效率工具"
        - "🛠️ 效率工具 / Mac 工具"
        - "🛠️ 效率工具 / 浏览器自动化工具"
        - "🛠️ 效率工具 / 个人知识管理与笔记软件"
        - "☁️ 云原生与自动化运维 (Cloud Native & DevOps)"
        - "☁️ 云原生与自动化运维 (Cloud Native & DevOps) / 🐳 容器编排与管理"
        - "☁️ 云原生与自动化运维 (Cloud Native & DevOps) / CI、CD 持续交付"
        - "📈 金融科技"
        - "📈 金融科技 / 量化交易"
  - type: input
    id: new_category
    attributes:
      label: 💡 或创建新分类 (支持多级，用 / 分隔)
      description: 例如 "后端 / Go / Web框架"
