name: Update README from New Issue

on:
  issues:
    types: [ opened ]

jobs:
  update-readme:
    if: contains(github.event.issue.labels.*.name, 'add-repo')
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: 提取 Issue 数据并更新 README
        id: update_readme
        run: |
          ISSUE_BODY='${{ github.event.issue.body }}'
          echo "$ISSUE_BODY" > issue_body.txt
          # 使用grep -P进行更可靠的提取，并处理多行内容
          CATEGORY=$(grep -A 1 "Category (title in README.md):" issue_body.txt | tail -1 | xargs)
          REPO_URL=$(grep -A 1 "Repository URL:" issue_body.txt | tail -1 | xargs)
          PROJECT_NAME=$(grep -A 1 "Project Name/Description:" issue_body.txt | tail -1 | xargs)
          LANGUAGE=$(grep -A 1 "Language (optional, but recommended if applicable):" issue_body.txt | tail -1 | xargs)
          
          
          # 输出用于调试
          echo "提取的数据:"
          echo "分类: $CATEGORY"
          echo "仓库URL: $REPO_URL"
          echo "项目名称: $PROJECT_NAME"
          echo "语言: $LANGUAGE"
          # 直接用 go run 执行
          if [ -n "$LANGUAGE" ]; then
            go run main.go addR -t "$CATEGORY" -r "$REPO_URL" -n "$PROJECT_NAME" -l "$LANGUAGE"
          else
            go run main.go addR -t "$CATEGORY" -r "$REPO_URL" -n "$PROJECT_NAME"
          fi
          # 检查 README.md 是否已修改
          git diff --quiet README.md || echo "readme_changed=true" >> $GITHUB_OUTPUT
        shell: bash

      - name: push
        if: steps.update_readme.outputs.readme_changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Docs: Add new entry from issue #${{ github.event.issue.number }}"
          git push

      - name: close Issue
        if: steps.update_readme.outputs.readme_changed == 'true'
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            该条目已成功添加到 README.md！谢谢您的贡献！
            Entry has been successfully added to README.md! Thank you for your contribution!
          token: ${{ secrets.GITHUB_TOKEN }}